# Generated by Django 5.2.7 on 2025-11-01 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_assistants_dash', '0001_initial'),
        ('teachers_dash', '0005_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingassistant',
            name='course',
        ),
        migrations.CreateModel(
            name='CourseAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='teachers_assistants_dash.teachingassistant')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='teachers_dash.course')),
            ],
            options={
                'unique_together': {('course', 'assistant')},
            },
        ),
    ]
