# Generated by Django 5.2.7 on 2025-11-02 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_assistants_dash', '0003_teachingassistant_email_and_more'),
        ('teachers_dash', '0006_exercise_exercisequestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingassistant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teachingassistant',
            name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='teachingassistant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teachingassistant',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teachingassistant',
            name='title',
        ),
        migrations.RemoveField(
            model_name='teachingassistant',
            name='user_id',
        ),
        migrations.CreateModel(
            name='TAExerciseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('time_limit_minutes', models.PositiveIntegerField(default=0)),
                ('structure_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='teachers_assistants_dash.teachingassistant')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_sessions', to='teachers_dash.course')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_sessions', to='teachers_dash.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='TAExerciseSessionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=150)),
                ('answers_json', models.JSONField(default=list)),
                ('total_checked_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='teachers_assistants_dash.taexercisesession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'student_id'], name='teachers_as_session_d3ec20_idx')],
            },
        ),
    ]
