# Generated by Django 5.2.7 on 2025-11-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_assistants_dash', '0004_remove_teachingassistant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassistant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teachingassistant',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teachingassistant',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teachingassistant',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teachingassistant',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms')], max_length=20),
        ),
        migrations.AddField(
            model_name='teachingassistant',
            name='user_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
