# Generated by Django 5.2.7 on 2025-11-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_assistants_dash', '0005_teachingassistant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taexercisesessionsubmission',
            name='group_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taexercisesessionsubmission',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
