# Generated by Django 5.2.7 on 2025-11-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_assistants_dash', '0006_taexercisesessionsubmission_group_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taexercisesessionsubmission',
            name='evidence_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taexercisesessionsubmission',
            name='evidence_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
