# Generated by Django 5.2.7 on 2025-11-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_assistants_dash', '0007_taexercisesessionsubmission_evidence_received_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taexercisesessionsubmission',
            name='evidence_decision',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='taexercisesessionsubmission',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='taexercisesessionsubmission',
            name='evidence_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
