# Generated by Django 5.2.7 on 2025-11-02 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_dash', '0001_initial'),
        ('teachers_dash', '0008_course_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExerciseGroupSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group_selections', to='teachers_dash.exercise')),
                ('group_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='teachers_dash.exercisegrouptime')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_selections', to='students_dash.student')),
            ],
            options={
                'unique_together': {('student', 'exercise')},
            },
        ),
    ]
