# Generated by Django 5.2.7 on 2025-11-01 09:38

import django.db.models.deletion
import teachers_dash.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_dash', '0002_teachercode_teacher_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='django_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user_uid',
            field=models.CharField(default=teachers_dash.models.generate_teacher_uid, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user_id',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
    ]
