# Generated by Django 5.2.7 on 2025-11-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_dash', '0003_teacher_django_user_teacher_user_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
