# Generated by Django 5.2.7 on 2025-11-02 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_dash', '0006_exercise_exercisequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseGroupTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_times', to='teachers_dash.exercise')),
            ],
        ),
    ]
