# Generated by Django 5.2.7 on 2025-11-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_dash', '0001_initial'),
        ('teachers_dash', '0007_exercisegrouptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='students_dash.student'),
        ),
    ]
